User/diegoarmstrong/vds/data processing
UBC-Solar/firmware_v3 pull request #125
Opened 2024-06-12 14:22 UTC by DiegoArmstrong

Added functionality to process CAN messages from the ADC readings for vds sensors.

2024-06-15 17:35 UTC, ishanjoshi23 requested changes

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Inc/can.h
> +#include "common.h"
This needs to be moved below to the `USER CODE BEGIN Includes` section. The autogenerator will remove this where it is right now.

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Inc/can.h
> +void CAN_SendShockTravel(VDS_Data_t *adc_data);
Good naming convention!

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Src/adc.c
> +  if (HAL_ADCEx_Calibration_Start(&hadc1) != HAL_OK){
I don't think we should be including this in production code, as recalibrating repeatedly would impact the characterization functions. @mjohal67 Please correct me if I am wrong.

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Src/can.c
> +    message.data[0] = adc_value.bytes.low;
All the `message.data[i]` can be combined into a for loop to reduce the code necessary for this.

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Src/can.c
> +    message.data[0] = adc_value.bytes.low;
All the `message.data[i]` can be combined into a for loop to reduce the code necessary for this.

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Src/can.c
> +void CAN_SendVDSDiagnostic(VDS_Data_t *vds_status){
@AarjavJain101 Will discuss the new diagnostic template with you soon.

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Src/main.c
> +  vds_data.adc_data.ADC_brake_pressure_1 = (24.55 * vds_data.adc_data.ADC_brake_pressure_1) + 1.925;
No magic numbers. Please define these as symbolic constants and name them appropriately.

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Src/main.c
> +void convertADCValue(void){
Please move helper functions to their own file. E.g., ADC helpers can be moved to the USER code part of the `adc.c` file. Such functions should be named like ADC_convert_ADC_Value where the function starts with the peripheral/file it lives in.

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Src/main.c
> +void processCANMessages(void)
Same for this function. Would be good if it was in can.c as CAN_process_CAN_Messages

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Src/main.c
> +    CAN_SendShockTravel(&vds_data);
Just like this! This is good naming.

2024-06-15 17:35 UTC, ishanjoshi23 commented on components/vds/Core/Src/main.c
> +  // Send diagnostic message every 5 seconds
@AarjavJain101 Will discuss this on Saturday

2024-06-15 17:35 UTC, ishanjoshi23 commented
Need  to add/review  averaging and add IWDG @makac1896

2024-06-15 18:02 UTC, DiegoArmstrong commented on components/vds/Core/Inc/can.h
> +void CAN_SendShockTravel(VDS_Data_t *adc_data);
Thanks bbg

2024-06-22 06:15 UTC, ishanjoshi23 commented
Changes look good. Merging into main feature branch

2024-06-22 06:15 UTC, merged