User/mjohal67/ecu comp current threshold
UBC-Solar/firmware_v3 pull request #151
Opened 2024-07-15 00:50 UTC by mjohal67

## Pull Request Description
Regulation 8.3.B states:
> All lithium based battery packs must have active protection such that over-voltage,
over-temperature (for charge and discharge rating), over-current and under-voltage cause the Main
Power Switch per 8.6.A to open and to electrically isolate the source or sink for the vehicle.

The "OR" statement at the end of this regulation caused us to have issues at scruitineering. We assumed that the over-temperature charge limit would be a trip, and that the over-temperature discharge limit would be a fault. However, the scruitineers required us to have a fault at 45C (trip at 44C), _and_ a fault at 65C (whereas before, we just had the trip at 45C and fault at 65C). 

They argue that this because, when you exceed any of the manufactuer's specifications, you should fault the pack. Thus, even though you're opening HLIM when you trip at 44C and requesting regen off (meaning you'd never reach 45C while charging), you still need to trip at 45C. 

## Monday Link

## Effected Components

- [ ] AMB
- [ ] BMS
- [ ] DID
- [ ] ECU
- [ ] MCB
- [ ] MDI
- [ ] TEL
- [ ] CI/CD

## Testing

- [x] Vehicle testing
- [x] Bench top testing
- [ ] Unit testing
- [x] Other (Comp 2024 scruitineering) 
- [ ] N/A

## Sanity check

- CAN ID table updated
- IOC updated and commited
- gitignore updated and commited
- [ ] Steps confirmed

## Sources

2024-07-16 13:45 UTC, ishanjoshi23 approved these changes

2024-07-16 14:30 UTC, Tik-Hakobyan approved these changes

2024-07-18 04:03 UTC, ishanjoshi23 requested changes
Remove AMB changes

2024-07-18 04:31 UTC, ishanjoshi23 approved these changes
I fixed the extra files added here

2024-07-18 04:44 UTC, merged

2025-06-18 02:07 UTC, mjohal67 commented
Related Monday update: https://ubcsolar26.monday.com/boards/7524358047/pulses/7524360025/posts/4176716691