User/matthewjegan/bms/ceedling
UBC-Solar/firmware_v3 pull request #16
Opened 2021-06-05 17:12 UTC by matthewjegan

Pull ceedling setup and shiftDchStatus fix discovered by unit tests to master branch

2021-06-05 19:34 UTC, a2k-hanlon requested changes
Let's get rid of all of the platformio stuff. Also, add all of the folders with stuff autogenerated by ceedling to a .gitignore.

We'll also look into a way to avoid having header files in the src folder.

2021-06-05 19:34 UTC, a2k-hanlon commented on components/bms/bms_master/project.yml
> +# Sample project C code is not presently written to produce a release artifact.
Do we need this template comment still?

2021-06-12 18:32 UTC, matthewjegan reviewed
Applied changes to maintain project structure with separate header files.
Removed build files and autogenerated code.

2021-06-12 18:57 UTC, a2k-hanlon approved these changes

2021-06-12 18:58 UTC, merged