User/evan o12/can comms diagnostic testing
UBC-Solar/firmware_v3 pull request #171
Opened 2024-11-11 07:30 UTC by EvanO12

## Pull Request Description

Can comms diagnostic struct, and functions. Keep track of failed can init, dropped tx, and rx messages. Function user can call to  access diagnostic data through struct.

## Monday Link

https://ubcsolar26.monday.com/boards/7524367653/pulses/7681393885/posts/3559718096

## Effected Components

-Libraries

## Testing

**- [ ] Bench top testing**

See monday update: https://ubcsolar26.monday.com/boards/7524367653/pulses/7595111315/posts/3610231936

## Sanity check

- CAN ID table updated
- IOC updated and commited
- gitignore updated and commited
- [ ] Steps confirmed

## Sources

2024-11-12 00:25 UTC, AarjavJain101 requested changes

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +	CAN_comms_diagnostic.comms_init_error = 0;
Lets use defines for the Errors. So define 0 as meaning something and 1 as meaning something. You dont need to have a TypeDef for the errors since there is not a lot going on here.

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +        return;
~Are you sure you want to return on a Tx error?~ **I should rephrase: Is there any reason to return at the end of the if? You are already finished the function.**

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +    	osDelay(1);
Why `osDelay(1)`?

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +           return; // TODO: Error handle
Again why return here. Also is this a better spot to do the dropped Tx message++?

If not, consider creating two diagnostic fields: one for dropped Queue Tx messages and one for dropped Tx with HAL CAN.

Additionally how do you want the user to use the diagnostic message struct?

Considering that we are going to have quite a few counters and such the total bytes dedicated to CAN comms diagnostics will be quite large IF we be too lenient with counter sizes. For now, if we have > 1 CAN messages dedicated ti CAN comms diagnostics it's not actually a bad thing. We can discuss this idea in an MMR for this project if necessary. For now, all we need is the struct with ALL diagnostics information.

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +          return; // TODO: Error handle
Do we want to return here? What about ++ to a diagnositc? If we return we lose ability to ever Rx again.

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +    diagnostic->dropped_rx_msg = CAN_comms_diagnostic.dropped_rx_msg;
Fun fact you can just do equals operator:

my_diagnostic = *can_comms_diagnositc;

And this will copy all the fields. This is more readable and safe if you add more fields to the diagnostic struct and forget to update this function.

2024-11-12 00:25 UTC, AarjavJain101 commented on components/tel/Core/Src/freertos.c
Why did `freertos.c` change? If it was a mistake I would untrack it from your branch. You can do this by running

`git checkout <BRANCH> -- path/to/file`

The goal of that command is to replace the file you specified with the copy on the branch you specified.
in your case
`git checkout origin/master -- components/tel/Core/Src/freertos.c`

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Inc/CAN_comms.h
> +   // ... More information ..
Remove this once you finish the PR

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Inc/CAN_comms.h
> +void CAN_comms_Diagnostic(CAN_comms_diagnostics_t* diagnostic);
Change function name to include the action it performs:

example: `CAN_comms_set_diagnostic`

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Inc/CAN_comms.h
>  void CAN_comms_Add_Tx_message(CAN_comms_Tx_msg_t* CAN_comms_Tx_msg);
Also I know you didnt change this but @kcgroulx is there any reason the Add Tx part is capitalized but the message part isnt? I think we should stay consistent with our naming.

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +        return;
Good. Makes sense to return here because you literally cannot do anything without the config parameters.

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +
Ight 3 new lines is excessive. make it 1

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +
Remove new line

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
>          /* Wait until there is a message in the queue */
Slide the comment **back** a space so its aligned

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +         if(HAL_OK != HAL_CAN_AddTxMessage(CAN_comms_config.hcan, &CAN_comms_Tx_msg.header, CAN_comms_Tx_msg.data, &can_mailbox))
Look at this in VSCode or some editor. Your indentation is very messed up
![image](https://github.com/user-attachments/assets/81a59298-4657-4585-813c-99bb888a9e70)

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +            // TODO: Error handle
Considering adding a diagnostic here.

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +    	osDelay(1);
I think the reason you were not able to receive messages as fast as 1 ms is because you have an `osDelay(1)` here. Why is there an `osDelay(1)` here? If you get rid of it do your testing again to see at what point does CAN comms fail.

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
>          /* Wait until there is a message in the queue */
Slide back the comment 1 space

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +
Remove new line

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> -            return; // TODO: Error handle
Fix the indentation
![image](https://github.com/user-attachments/assets/336f601e-853a-4847-b01f-76b0cd635258)

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +          return; // TODO: Error handle
If getting from the queue fails are sure you want to return? What about adding a diagnostic counter here?

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
>      if(osOK != osMessageQueuePut(CAN_comms_Rx_queue, &CAN_Rx_msg, 0, 0))
In the `return` statement in the `if` above consider doing a ++ for a counter
![image](https://github.com/user-attachments/assets/087107bc-6521-47e2-9fd9-6799ecd4d460)

2024-11-12 00:25 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +    //... add more
Based on my comment above, you will not need to `add more...`

2024-11-12 01:26 UTC, EvanO12 commented on libraries/CAN_comms/Src/CAN_comms.c
> +          return; // TODO: Error handle
I think kyle was fixing this in his latest CAN comms version

2024-11-12 03:22 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +    .priority = (osPriority_t) osPriorityLow,
Lets ask @kcgroulx if this should be `osPriorityHigh`.

2024-11-12 03:22 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +#define COMMS_INIT_FAILURE 1
Align all the defines.

2024-11-12 03:22 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +        uint32_t can_mailbox; // Not used
Check it out in VSCode, still looks really unaligned. I had `git pull`ed
![image](https://github.com/user-attachments/assets/02a2ee8b-ab94-4978-9e51-f03398c2724c)

2024-11-12 03:22 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
>          else
indent the content inside the `if` statement
![image](https://github.com/user-attachments/assets/44308ad3-5b80-4c64-ae97-3f9690e66d33)

2024-11-12 03:22 UTC, AarjavJain101 commented on libraries/CAN_comms/Src/CAN_comms.c
> +          return; // TODO: Error handle
Have you checked ^^^ out @EvanO12?

2024-11-14 06:02 UTC, EvanO12 commented on libraries/CAN_comms/Src/CAN_comms.c
> +           return; // TODO: Error handle
@kcgroulx Can I get your input on this?

2024-11-14 06:02 UTC, EvanO12 commented on libraries/CAN_comms/Src/CAN_comms.c
> +          return; // TODO: Error handle
@kcgroulx What are your thoughts on this?

2024-11-20 03:38 UTC, kcgroulx requested changes

2024-11-20 03:38 UTC, kcgroulx commented on libraries/CAN_comms/Src/CAN_comms.c
> +}
These function are kind of redundant since they're only 1 line.

2024-11-20 03:38 UTC, kcgroulx commented on libraries/CAN_comms/Src/CAN_comms.c
> +}
Move this function, this section is for the callbacks generated by cubeMX

2024-11-20 03:38 UTC, kcgroulx commented on libraries/CAN_comms/Inc/CAN_comms.h
> +* @param dropped_tx_msg: Count of dropped messages in the TX buffer
Specify that they are dropped in the queue

2024-11-20 03:56 UTC, kcgroulx approved these changes

2024-11-21 08:16 UTC, AarjavJain101 approved these changes
nice

2024-11-21 08:18 UTC, merged